### PR TITLE
Add a parser for a list of links (see issue #39)

### PR DESCRIPTION
**Pull request by frinkelpi**
See https://github.com/pirate/bookmark-archiver/pull/58 and the comments therein. Thanks, and don't hesitate if you have any question on the changes.

### CODE REVIEW

**Comment by issmirnov** [comment]
This is an awesome feature. Does this project still hold your interest and would you find time to fix the merge conflicts?

**Comment by issmirnov** [comment]
Ah, interesting. Yes, this makes sense. I just created a small `bookmarks.html` with fake data, ran into this issue.

What ID scheme did you decide to use? Domains + page path hash, or something else?

**Comment by pirate** [comment]
Full url actually, including scheme, it's what the Internet Archive uses and I'd rather archive two similar urls separately than merge two different pages into one by accident.

I'll probably drop trailing slashes, but http and https would be different links.  Most sites redirect to https now anyways, so I doubt it's going to be an issue.

**Comment by pirate** [comment]
I recommend using @nodiscc's [script to convert a plain-text list](https://github.com/pirate/bookmark-archiver/issues/39#issuecomment-320066412) into a valid netscape html format for now.

**Comment by issmirnov** [comment]
Awesome, that also makes my personal use case way simpler. Planning to archive all links on my wiki, so having a deterministic prefix is ideal.

If there are any subtasks you can farm out, I'd be happy to take a stab at them.

**Comment by pirate** [comment]
That would be awesome, thanks @issmirnov!  This is a good first ticket to get familiar with the codebase: https://github.com/pirate/bookmark-archiver/issues/38

It involves adding a couple new options in `config.py`, and adding some logic to skip certain urls when creating the index and archive.

**Comment by pirate** [comment]
I'm going to close this because I'm removing timestamps as the unique key and using url hashes instead in the new layout as mentioned here: 
https://github.com/pirate/bookmark-archiver/issues/120

Once unique ordering is established separately from timestamps, link parsing from a plain text list of links will be trivial and I'll make sure I push it with the new layout changes.

**Comment by sbrl** [comment]
Awesome, thanks! I guess it'll be in the next release?

**Comment by nodiscc** [comment]
Using URL hashes is very nice and i drew the same conclusion when working on my own archiving tool (now unmaintained). Good luck with the next release

**Pull request closed without merging**
