### PR TITLE
Refactor linkinfo

### PR DESCRIPTION
**Pull request by issmirnov**
Pulling in another change by @frinkelpi from #59. Sending in a series of small commits to ensure tests pass and make this easy to review.

Tested: `./archive archiver/tests/rss_export.xml`

### CODE REVIEW

**Comment by issmirnov** [comment]
Ping @pirate - any concerns with merging this one?

**Comment by pirate** [comment]
`def basic_link_info(url, f, title=None, time=datetime.now(), tags=""):`

This instantiates one `datetime.now()` at parse-time, not each time the function is called. Is that the intended behavior?

**Comment by issmirnov** [comment]
That's a good catch. It would make more sense to evaluate it at call time.

Side note: I'm swamped at work the past few days (still at the office at 9pm my time) so I don't think I'll have much time to massage the PR's on this project. My sincere apologies about that. I'll try to make my way back as soon as I can, but it may take some time. If this PR isn't useful in it's current state, feel free to close. I've enabled edits for you in case you want to tweak it.

**Comment by pirate** [comment]
I really appreciate the work you've put in so far, but I think I'm going to close this since I have heavy refactors planned for this area of the code anyway.

I'm planning on splitting out parsing and archiving into a plugin-style architecture so people can write their own modules, this will involve a lot of code cleanup anyway and I will certainly take inspiration from this PR to make aspects of it more functional.

@frinkelpi please don't be discouraged by this, I appreciate the contributions and I think I should do a better job of publishing my roadmap for future improvement so people don't bother refactoring areas of the code I plan to remove/change heavily myself in the near future.

**Pull request closed without merging**
